# Generated by Django 5.2.17 on 2026-09-03 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RepairRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skills_required', models.CharField(choices=[('MOBILE_REPAIR', 'Mobile_Repair'), ('LAPTOP_REPAIR', 'Laptop_Repair'), ('PLUMBER', 'Plumber'), ('ELECTRICIAN', 'Electrician')], max_length=100)),
                ('requirement', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.customerprofile')),
            ],
        ),
    ]
