# Generated by Django 5.2.17 on 2026-09-03 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('is_accepted', models.BooleanField(default=False)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.repairrequest')),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.technicianprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Repair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed')], default='PENDING', max_length=10)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('accepted_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='technician.sentrequest')),
            ],
        ),
    ]
