# Generated by Django 5.2.17 on 2026-09-04 16:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='technicianprofile',
            old_name='is_avaliable',
            new_name='is_available',
        ),
        migrations.RemoveField(
            model_name='customerprofile',
            name='latitute',
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='latitude',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='technicianprofile',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='longitude',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='technicianprofile',
            name='average_rating',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='technicianprofile',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='technicianprofile',
            name='experience',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='technicianprofile',
            name='skill',
            field=models.CharField(blank=True, choices=[('MOBILE_REPAIR', 'Mobile Repair'), ('LAPTOP_REPAIR', 'Laptop Repair'), ('PLUMBER', 'Plumber'), ('ELECTRICIAN', 'Electrician')], max_length=100, null=True),
        ),
    ]
